Models/ErrorViewModel.cs
namespace EmployeeRateCard.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/PaySummaryViewModel.cs
using EmployeeRating.Lib.Core.Models;

namespace EmployeeRateCard.Models
{
	public class PaySummaryViewModel
	{
        public string EmployeeName { get; set; }
        public string EmployeeNumber { get; set; }
        public string EarningsCode { get; set; }
        public decimal TotalHours { get; set; }
        public decimal TotalPayAmount { get; set; }
        public decimal RateOfPay { get; set; }
        public string Job { get; set; }
        public string Dept { get; set; }

        public List<PaySummaryViewModel> ConvertToPaySummariesVMList (IEnumerable<PaySummaryModel> paySummaries)
        {
            List<PaySummaryViewModel> paySummariesList = new();
            foreach (var paySummary in paySummaries)
            {
                PaySummaryViewModel model = new()
                {
                    EmployeeName = paySummary.EmployeeName,
                    EmployeeNumber = paySummary.EmployeeNumber,
                    EarningsCode = paySummary.EarningsCode,
                    TotalHours = paySummary.TotalHours,
                    TotalPayAmount = paySummary.TotalPayAmount,
                    RateOfPay = paySummary.RateOfPay,
                    Job = paySummary.Job,
                    Dept = paySummary.Dept,
                };
                paySummariesList.Add(model);
            }
            return paySummariesList;
        }
    }
}

Models/RateCardViewModel.cs
using EmployeeRating.Lib.Core.Models;

namespace EmployeeRateCard.Models
{
	public class RateCardViewModel
	{
		public Guid Id { get; set; }
		public string Job { get; set; }
        public string Dept { get; set; }
		public DateTime EffectiveStart { get; set; }
		public DateTime EffectiveEnd { get; set; }
		public decimal HourlyRate { get; set; }

		public List<RateCardViewModel> convertToRateCardVMList(IEnumerable<RateCardModel> ratecards)
		{
			List<RateCardViewModel> rateCards = new();
			foreach (var ratecard in ratecards)
			{
				RateCardViewModel model = new()
				{
					Id = ratecard.Id,
					Job = ratecard.Job,
					Dept = ratecard.Dept,
					EffectiveStart = ratecard.EffectiveStart,
					EffectiveEnd = ratecard.EffectiveEnd,
					HourlyRate = ratecard.HourlyRate,
				};
				rateCards.Add(model);
            }
			return rateCards;

        }
	}
}

Models/TimeCardViewModel.cs
using EmployeeRating.Lib.Core.Models;

namespace EmployeeRateCard.Models
{
	public class TimeCardViewModel
	{
        public Guid Id { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeNumber { get; set; }
        public DateTime DateWorked { get; set; }
        public string EarningsCode { get; set; }
        public string JobWorked { get; set; }
        public string DeptWorked { get; set; }
        public decimal Hours { get; set; }
        public decimal Rate { get; set; }
        public decimal Bonus { get; set; }

        public List<TimeCardViewModel> ConverToTimeCardVMList(IEnumerable<TimeCardModel> timecards)
        {
            List<TimeCardViewModel> timeCards = new();
            foreach (var timecard in timecards)
            {
                TimeCardViewModel model = new()
                {
                    Id = timecard.Id,
                    EmployeeName = timecard.EmployeeName,
                    EmployeeNumber = timecard.EmployeeNumber,
                    DateWorked = timecard.DateWorked,
                    EarningsCode = timecard.EarningsCode,
                    JobWorked = timecard.JobWorked,
                    DeptWorked = timecard.DeptWorked,
                    Hours = timecard.Hours,
                    Rate = timecard.Rate,
                    Bonus = timecard.Bonus
                };
                timeCards.Add(model);
            }
            return timeCards;
        }
    }
}

Controllers/HomeController.cs
using EmployeeRateCard.Models;
using EmployeeRating.Lib.Core;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeRateCard.Controllers
{
	public class HomeController : Controller
	{
        private readonly IRatingService _ratingService;		

        private readonly ILogger<HomeController> _logger;
		List<PaySummaryViewModel> _paySummariesListVM = new();
		PaySummaryViewModel PaySummaryVM = new();

        public HomeController(IRatingService ratingService, ILogger<HomeController> logger)
        {
            _ratingService = ratingService;
            _logger = logger;
        }

       

		public async Task<IActionResult> Index()
		{
			var ratingResponse = await _ratingService.GetRateCards();
            var timeCardresponse = await _ratingService.GetTimeCards();
            var summary = _ratingService.GeneratePaySummary(timeCardresponse.ToList(), ratingResponse.ToList());
            _paySummariesListVM = PaySummaryVM.ConvertToPaySummariesVMList(summary);
            return View(_paySummariesListVM);
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/RatecardController.cs
using EmployeeRateCard.Models;
using EmployeeRating.Lib.Core;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeRateCard.Controllers
{
	public class RatecardController : Controller
	{
		private readonly IRatingService _ratingService;

		List<RateCardViewModel> rateCardVMList = new();
		RateCardViewModel rateCardVM = new();
        public RatecardController(IRatingService ratingService)
		{
			_ratingService = ratingService;
		}
		public async Task<IActionResult> Index()
		{
			var ratingResponse =await _ratingService.GetRateCards();
			rateCardVMList = rateCardVM.convertToRateCardVMList(ratingResponse);
            return View(rateCardVMList);
		}
	}
}

Controllers/TimecardController.cs
using EmployeeRateCard.Models;
using EmployeeRating.Lib.Core;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeRateCard.Controllers
{
	public class TimecardController : Controller
	{
        private readonly IRatingService _ratingService;
		List<TimeCardViewModel> _timeCardVMList = new();
		TimeCardViewModel timeCardVM = new();
        public TimecardController(IRatingService ratingService)
		{
			_ratingService = ratingService;
		}
        public async Task<IActionResult> Index()
		{
			var response = await _ratingService.GetTimeCards();
			_timeCardVMList = timeCardVM.ConverToTimeCardVMList(response.ToList());
           
            return View(_timeCardVMList);
		}
	}
}

Views/Home/Index.cshtml
@model List<EmployeeRateCard.Models.PaySummaryViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Summary</h1>
    <table class="table table-bordered mt-4">
        <thead>
            <tr>

                <th>EmployeeName</th>
                <th>EmployeeNumber</th>
                <th>EarningsCode</th>
                <th>TotalHours</th>
                <th>TotalPayAmount</th>
                <th>RateOfPay</th>
                <th>Job</th>
                <th>Dept</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.EmployeeName</td>
                    <td>@item.EmployeeNumber</td>
                    <td>@item.EarningsCode</td>
                    <td>@item.TotalHours</td>
                    <td>@item.TotalPayAmount</td>
                    <td>@item.RateOfPay</td>
                    <td>@item.Job</td>
                    <td>@item.Dept</td>
                </tr>

            }
        </tbody>
    </table>

</div>

Views/Ratecard/Index.cshtml
@model List<EmployeeRateCard.Models.RateCardViewModel>
@{   
    ViewData["Title"] = "Rate Card";
}
<div class="text-center">
    <h1 class="display-4">Rate Card</h1>
    <table class="table table-bordered mt-4">
        <thead>
            <tr>

                <th>Id</th>
                <th>Job</th>
                <th>Dept</th>
                <th>Effective Start</th>
                <th>Effective End</th>
                <th>HourlyRate</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Job</td>
                    <td>@item.Dept</td>
                    <td>@item.EffectiveStart.ToString("MM/dd/yyyy")</td>
                    <td>@item.EffectiveEnd.ToString("MM/dd/yyyy")</td>
                    <td>@item.HourlyRate</td>
                </tr>
                
            }
        </tbody>
    </table>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeRateCard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeRateCard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeRateCard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Timecard" asp-action="Index">Time Card</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ratecard" asp-action="Index">Rate Card</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EmployeeRateCard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Timecard/Index.cshtml
@model List<EmployeeRateCard.Models.TimeCardViewModel>

@{
    ViewData["Title"] = "Time Card";
}
<div class="text-center">
    <h1 class="display-4">Time Card</h1>
    <table class="table table-bordered mt-4">
        <thead>
            <tr>

                <th>Id</th>
                <th>Employee Name</th>
                <th>Employee Number</th>
                <th>Date Worked</th>
                <th>Employee Code</th>
                <th>Job Worked</th>
                <th>Dept Worked</th>
                <th>Hours</th>
                <th>Rate</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.EmployeeName</td>
                    <td>@item.EmployeeNumber</td>
                    <td>@item.DateWorked.ToString("MM/dd/yyyy")</td>
                    <td>@item.EarningsCode</td>
                    <td>@item.JobWorked</td>
                    <td>@item.DeptWorked</td>
                    <td>@item.Hours</td>
                    <td>@item.Rate</td>
                </tr>

            }
        </tbody>
    </table>
</div>